# Generated by Django 4.0.5 on 2022-07-04 06:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_admin_phone_alter_admin_email_alter_parent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='full name'),
            preserve_default=False,
        ),
    ]
