# Generated by Django 4.0.5 on 2022-07-04 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=12, verbose_name='phone'),
            preserve_default=False,
        ),
    ]
