# Generated by Django 4.0.5 on 2022-07-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='email',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='phone',
        ),
    ]
