export const ADMIN_USER_LOADED = "ADMIN_USER_LOADED";
export const ADMIN_USER_FAILED = "ADMIN_USER_FAILED";
export const PARENT_USER_LOADED = "PARENT_USER_LOADED";
export const PARENT_USER_FAILED = "PARENT_USER_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_PARENT_SUCCESS = "REGISTER_PARENT_SUCCESS";
export const REGISTER_PARENT_FAILED = "REGISTER_PARENT_FAILED";
export const REGISTER_ADMIN_SUCCESS = "REGISTER_ADMIN_SUCCESS";
export const REGISTER_ADMIN_FAILED = "REGISTER_ADMIN_FAILED";

export const ADD_KID = "ADD_KID";
export const ADD_KID_FAIL = "ADD_KID_FAIL";
export const GET_KID = "GET_KID";
export const GET_KID_FAIL = "GET_KID_FAIL";
export const UPDATE_KID = "UPDATE_KID";
export const UPDATE_KID_FAILED = "UPDATE_KID_FAILED";
export const DELETE_KID = "DELETE_KID";
export const GET_ALL_KIDS = "GET_ALL_KIDS";
export const GET_ALL_KIDS_FAIL = "GET_ALL_KIDS_FAIL";
export const ENROLL_KID = "ENROLL_KID";
export const ENROLL_KID_FAILED = "ENROLL_KID_FAILED";

export const GET_PROGRAMMES = "GET_PROGRAMMES";
export const GET_PROGRAMMES_FAIL = "GET_PROGRAMMES_FAIL";
export const GET_COHORTS = "GET_COHORTS";
export const GET_COHORTS_FAIL = "GET_COHORTS_FAIL";
