# Generated by Django 4.0.5 on 2022-07-16 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='parent_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='kids', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
