# Generated by Django 4.0.5 on 2022-07-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0002_kid_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='cohort_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='kid',
            name='programme_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
