# Generated by Django 4.0.5 on 2022-07-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0003_kid_cohort_id_kid_programme_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='cohort_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='kid',
            name='programme_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
