# Generated by Django 4.0.5 on 2022-07-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='duration',
            field=models.IntegerField(default=16),
            preserve_default=False,
        ),
    ]
